export const PERMISSIONS = {
  VIEW_EMPLOYEES: 'view_employees',
  MANAGE_EMPLOYEES: 'manage_employees',
  
  VIEW_ATTENDANCE: 'view_attendance',
  MANAGE_ATTENDANCE: 'manage_attendance',
  
  VIEW_HOLIDAYS: 'view_holidays',
  MANAGE_HOLIDAYS: 'manage_holidays',
  
  VIEW_LEAVES: 'view_leaves',
  MANAGE_LEAVES: 'manage_leaves',
  
  VIEW_BANK_ACCOUNTS: 'view_bank_accounts',
  MANAGE_BANK_ACCOUNTS: 'manage_bank_accounts',
  
  VIEW_DOCUMENTS: 'view_documents',
  MANAGE_DOCUMENTS: 'manage_documents',
  
  VIEW_ROLES: 'view_roles',
  MANAGE_ROLES: 'manage_roles',
};

// If any of these permissions are present, the sidebar item is visible
export const SIDEBAR_PERMISSIONS = {
  EMPLOYEES: [PERMISSIONS.VIEW_EMPLOYEES, PERMISSIONS.MANAGE_EMPLOYEES],
  ATTENDANCE: [PERMISSIONS.VIEW_ATTENDANCE, PERMISSIONS.MANAGE_ATTENDANCE],
  HOLIDAYS: [PERMISSIONS.VIEW_HOLIDAYS, PERMISSIONS.MANAGE_HOLIDAYS],
  LEAVES: [PERMISSIONS.VIEW_LEAVES, PERMISSIONS.MANAGE_LEAVES],
  PAYROLL: [PERMISSIONS.VIEW_BANK_ACCOUNTS, PERMISSIONS.MANAGE_BANK_ACCOUNTS],
  DOCUMENTS: [PERMISSIONS.VIEW_DOCUMENTS, PERMISSIONS.MANAGE_DOCUMENTS],
  ROLES: [PERMISSIONS.VIEW_ROLES, PERMISSIONS.MANAGE_ROLES],
};
